TRUTH = (
     "Who is your pirst lope?"
     "Confess! Have you ever stolen your parents' money?",
     "How many ex's do you have?"
     "Tell me about the problem you remember the most at school."
     "Choose a handsome guy or a rich guy? But not handsome",
     "If you are a girl, are you willing to be my owner's girlfriend @XFLSkyzo",
     "What do you think is the best moment in your life?"
     "Name 100 things about your friend",
     "Choose a pretty girl or a fake girl?",
     "What do you think is the biggest fear?"
     "Tell me something before you break up with your boyfriend",
     "What is your ideal type of girl? Are you big? Tell me what type you are",
     "What is your ideal type of guy?",
     "Try to tag the person you love the most here.",
     "Hayoo, when was the last time you were so and so?",
     "Tell me your life story :')",
     "@X_MEN_T I think he's handsome, let's chat, then ask him out hehe ️WARNING this is specifically for girls!",
  
)

DARE = ​​(
     "Show the most embarrassing photos on your phone"
     "Show the last five people you chatted with and what their messages were",
     "Say, I'm ugly 5 times with voice notes",
     "Eat raw garlic",
     "Equalize 100 squads in pubg or free fire",
     "Keep three ice cubes in your mouth until it melts",
     "Say something dirty to the person on your left. You have friends!",
     "Give a foot massage to the person on your right",
     "Put 10 different available liquids into a cup and drink it",
     "Say the first word that comes to your mind",
     "Give a lap dance to someone of your choice",
     "Take off the four clothes",
     "Like the first 15 posts on your Facebook newsfeed",
     "Eat a spoonful of salt",
     "Close your eyes until you leave again",
     "Send sex to the last person in your phone contact",
     "Show off your orgasmic face",
     "Eat bananas seductively",
     "Empty your wallet and show everyone what's in it",
     "Do your best sexy crawl",
     "Pretend to be the person on your right for 10 minutes",
     "Eat a snack without using your hands",
     "Say two honest things about everyone in the group",
     "Twerk for a bit",
     "Try to make the group members laugh as quickly as possible",
     "Try to put your whole fist in your mouth",
     "Tell everyone a shameful story about yourself",
     "Try to lick your elbow",
     "Post the oldest selfie on your phone on Instagram Stories",
     "Tell me the saddest story you know",
     "Howling like a wolf for two minutes",
     "Dance without music for two minutes",
     "Pole dance with imaginary poles",
     "Let other people tickle you and try not to laugh"
     "Put snacks in your mouth at once as much as you can",
     "Submit your latest selfie.",
     "Send your ugliest selfie.",
     "Send screenshot of your facebook search history",
     "Send a screenshot of your gallery.",
     "Send screenshot of your messenger inbox",
     "Say something very intimate.",
     "Send screenshot of your twitter inbox",
     "Send a screenshot of your home screen.",
     "Send a cover of your favorite song.",
     "Do a lyric joke on someone and send the proof.",
     "Acknowledge that you have a crush on your current classmate. ❤️",
     "Reveal who your true love is.",
     "Send a screenshot of your gallery.",
     "Say I love you to @X_MEN_T.",
     "Make your crush's picture as a chat wallpaper.",
     "Tell @X_MEN_T he's handsome",
)
